name: Ormolu Formatting Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Stack
      - name: Set up Stack
        uses: haskell/actions/setup@v2
        with:
          stack-version: "latest"

      # Step 3: Install Ormolu using Stack
      - name: Install Ormolu
        run: |
          stack install ormolu

      # Step 4: Run Ormolu in check mode
      - name: Run Ormolu Check
        run: |
            ~/.local/bin/ormolu --mode check $(find src app test -name '*.hs')

      # Step 5: Provide feedback if formatting issues are found
      - name: Formatting Check Feedback
        if: ${{ failure() }}
        run: |
            echo "❌ Ormolu formatting issues detected. Please run the following command locally to fix:"
            echo "ormolu --mode inplace \$(find src app test -name '*.hs')"
